# Generated by Django 3.1.2 on 2020-10-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201013_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
